### ISSUE TITLE
Running Pashua script

### ISSUE THREAD

**Issue by FedeCuci** [BlueM/Pashua-Binding-Python#2]
Hello, I am not able to run a Pashua script, it says:

Pashua command not found

or:

import error no module named Pashua

Any advice would be appreciated, Thank you

**Comment by BlueM** [comment]
There is no info on the required context, i.e.: what is installed and where, and from which directory are you trying to run the script?

**Comment by FedeCuci** [comment]
Hello BlueM,

That is the problem i don't understand where you are supposed to run the script from, (IF there is a specific directory) and if so, how do i run it? I have Pashua installed in my applications. I have also installed Pashua.py and example.py and i put them in the mac os folder within the Pashua.app. i use textwrangler as my text editor and i am used to run python scripts with terminal with the following command:

python filename.py

although I am in the directory as the file is, when i type:

Pashua filename.pash

it gives me the error i have mentioned in the previous comment!

Thank you!

![pashua ss 1](https://cloud.githubusercontent.com/assets/19730248/17566356/562505fc-5f3b-11e6-92b1-4e7943cf7302.png)
![pashua ss 2](https://cloud.githubusercontent.com/assets/19730248/17566355/56236936-5f3b-11e6-8bb8-00b19bbb5148.png)

The path name looks like this:
/Applications/Pashua.app/Contents/MacOS/Pashua-Binding-Python-master/Pashua.py

**Comment by BlueM** [comment]
- Just put Pashua in `/Applications` (or another of the supported places – see Python module source). Do _not_ modify `Pashua.app`. As it seems you have done this, just remove it and replace it with a fresh copy.
- Download (Zip or `git clone`) the binding’s sources and unzip (if zipped). Then, just run `example.py`. It will use the module, and it will find `Pashua.app`. The binding can be anywhere you like, and your working directory can be anything you like – as long as you use the absoute path to `example.py`, if it’s not in `$PATH`. The only restriction is: `example.py` expects `Pashua.py` in a place where it can be found via `sys.path`.

**Comment by FedeCuci** [comment]
Hello BlueM!

Everything works and it was much easier than i thought!

You were my last hope, i had almost given up searching!!

If i will have more problems (since i am a starter), in order to contact you, should i just post an issue here?

Thank you so much!

**Comment by BlueM** [comment]
You’re welcome.

Regarding posting questions here: Depends. This is an issue tracker, not a support forum, so it should be primarily used for reporting general issues.
